"""
Feature Registry, Domain Categorization, and Plain-English Templates for Phase 7 Explainability.

Provides a comprehensive, verified metadata dictionary for all 55 predictive model features,
defining human-friendly display names, domain categories, measurement units, standardized
reason code identifiers, and formatted risk/mitigating explanation templates.

Governance & Safety:
- Categorical features (merchant_category, job_category) are never described using internal ordinal numeric codes.
- Model-derived reason codes are strictly distinct from deterministic business rule codes.
- Templates are tailored to assist fraud analysts in auditability and case review.
"""

from typing import Dict, Any, Mapping
from types import MappingProxyType

from ml.models.config import PREDICTIVE_FEATURE_COLUMNS


FEATURE_REGISTRY: Dict[str, Dict[str, Any]] = {
    # ---------------------------------------------------------
    # Canonical Numeric Features (6)
    # ---------------------------------------------------------
    "amount": {
        "display_name": "Transaction Amount",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "HIGH_TRANSACTION_AMOUNT",
        "risk_headline": "Elevated Transaction Amount",
        "mitigating_headline": "Standard Transaction Amount",
        "risk_template": "Transaction amount of ${raw_value:,.2f} is significantly elevated and contributes to higher fraud risk.",
        "mitigating_template": "Transaction amount of ${raw_value:,.2f} is within normal spending bounds.",
        "is_categorical": False,
    },
    "cardholder_lat": {
        "display_name": "Cardholder Latitude",
        "category": "GEOGRAPHY",
        "unit": "degrees",
        "reason_code": "ANOMALOUS_CARDHOLDER_LATITUDE",
        "risk_headline": "Atypical Cardholder Location (Latitude)",
        "mitigating_headline": "Expected Cardholder Location (Latitude)",
        "risk_template": "Cardholder latitude ({raw_value:.4f}°) exhibits statistical risk in regional modeling.",
        "mitigating_template": "Cardholder latitude ({raw_value:.4f}°) aligns with common geographic patterns.",
        "is_categorical": False,
    },
    "cardholder_long": {
        "display_name": "Cardholder Longitude",
        "category": "GEOGRAPHY",
        "unit": "degrees",
        "reason_code": "ANOMALOUS_CARDHOLDER_LONGITUDE",
        "risk_headline": "Atypical Cardholder Location (Longitude)",
        "mitigating_headline": "Expected Cardholder Location (Longitude)",
        "risk_template": "Cardholder longitude ({raw_value:.4f}°) exhibits statistical risk in regional modeling.",
        "mitigating_template": "Cardholder longitude ({raw_value:.4f}°) aligns with common geographic patterns.",
        "is_categorical": False,
    },
    "merchant_lat": {
        "display_name": "Merchant Latitude",
        "category": "GEOGRAPHY",
        "unit": "degrees",
        "reason_code": "ANOMALOUS_MERCHANT_LATITUDE",
        "risk_headline": "Atypical Merchant Location (Latitude)",
        "mitigating_headline": "Expected Merchant Location (Latitude)",
        "risk_template": "Merchant location latitude ({raw_value:.4f}°) shows anomalous geographic correlation.",
        "mitigating_template": "Merchant location latitude ({raw_value:.4f}°) is within standard distribution.",
        "is_categorical": False,
    },
    "merchant_long": {
        "display_name": "Merchant Longitude",
        "category": "GEOGRAPHY",
        "unit": "degrees",
        "reason_code": "ANOMALOUS_MERCHANT_LONGITUDE",
        "risk_headline": "Atypical Merchant Location (Longitude)",
        "mitigating_headline": "Expected Merchant Location (Longitude)",
        "risk_template": "Merchant location longitude ({raw_value:.4f}°) shows anomalous geographic correlation.",
        "mitigating_template": "Merchant location longitude ({raw_value:.4f}°) is within standard distribution.",
        "is_categorical": False,
    },
    "city_pop": {
        "display_name": "City Population",
        "category": "GEOGRAPHY",
        "unit": "people",
        "reason_code": "UNUSUAL_CITY_POPULATION",
        "risk_headline": "Low Population Density Region",
        "mitigating_headline": "Standard Population Density",
        "risk_template": "Originating city population of {raw_value:,.0f} residents exhibits higher relative risk variance.",
        "mitigating_template": "Originating city population of {raw_value:,.0f} residents is typical.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Categorical Predictors (2)
    # ---------------------------------------------------------
    "merchant_category": {
        "display_name": "Merchant Category",
        "category": "CATEGORICAL",
        "unit": "category",
        "reason_code": "HIGH_RISK_MERCHANT_CATEGORY",
        "risk_headline": "Elevated-Risk Merchant Category",
        "mitigating_headline": "Low-Risk Merchant Category",
        "risk_template": "Merchant category '{raw_value}' historically carries elevated fraud propensity.",
        "mitigating_template": "Merchant category '{raw_value}' is historically associated with low fraud incidence.",
        "is_categorical": True,
    },
    "job_category": {
        "display_name": "Cardholder Job Category",
        "category": "CATEGORICAL",
        "unit": "category",
        "reason_code": "ANOMALOUS_JOB_CATEGORY",
        "risk_headline": "Atypical Account Profile Job Category",
        "mitigating_headline": "Standard Account Profile Job Category",
        "risk_template": "Account profile job category '{raw_value}' shows anomalous correlation with current purchase vector.",
        "mitigating_template": "Account profile job category '{raw_value}' is consistent with expected usage.",
        "is_categorical": True,
    },

    # ---------------------------------------------------------
    # Temporal & Calendar Features (11)
    # ---------------------------------------------------------
    "transaction_hour": {
        "display_name": "Transaction Hour",
        "category": "TEMPORAL",
        "unit": "hour",
        "reason_code": "OFF_HOURS_TRANSACTION_TIME",
        "risk_headline": "Atypical Transaction Hour",
        "mitigating_headline": "Standard Daytime Transaction Hour",
        "risk_template": "Transaction occurred at {raw_value:02.0f}:00 hours, an atypical time for this account.",
        "mitigating_template": "Transaction occurred at {raw_value:02.0f}:00 hours during standard business hours.",
        "is_categorical": False,
    },
    "day_of_week": {
        "display_name": "Day of Week",
        "category": "TEMPORAL",
        "unit": "day (0-6)",
        "reason_code": "UNUSUAL_DAY_OF_WEEK",
        "risk_headline": "Atypical Day of Week",
        "mitigating_headline": "Standard Day of Week",
        "risk_template": "Transaction occurred on day of week {raw_value:.0f}, which exhibits higher risk variance.",
        "mitigating_template": "Transaction occurred on day of week {raw_value:.0f} matching normal usage.",
        "is_categorical": False,
    },
    "day_of_month": {
        "display_name": "Day of Month",
        "category": "TEMPORAL",
        "unit": "day (1-31)",
        "reason_code": "UNUSUAL_DAY_OF_MONTH",
        "risk_headline": "Atypical Day of Month",
        "mitigating_headline": "Standard Day of Month",
        "risk_template": "Transaction occurred on day {raw_value:.0f} of the month.",
        "mitigating_template": "Transaction timing on day {raw_value:.0f} is consistent with account cadence.",
        "is_categorical": False,
    },
    "month": {
        "display_name": "Transaction Month",
        "category": "TEMPORAL",
        "unit": "month (1-12)",
        "reason_code": "SEASONAL_ANOMALY",
        "risk_headline": "Seasonal Activity Anomaly",
        "mitigating_headline": "Standard Monthly Pattern",
        "risk_template": "Transaction month ({raw_value:.0f}) reflects seasonal risk fluctuations.",
        "mitigating_template": "Transaction month ({raw_value:.0f}) aligns with baseline activity.",
        "is_categorical": False,
    },
    "week_of_year": {
        "display_name": "Week of Year",
        "category": "TEMPORAL",
        "unit": "week (1-53)",
        "reason_code": "UNUSUAL_WEEK_OF_YEAR",
        "risk_headline": "Atypical Calendar Week",
        "mitigating_headline": "Standard Calendar Week",
        "risk_template": "Transaction timing during calendar week {raw_value:.0f} shows unusual behavioral shift.",
        "mitigating_template": "Transaction timing during calendar week {raw_value:.0f} is standard.",
        "is_categorical": False,
    },
    "is_weekend": {
        "display_name": "Weekend Transaction Indicator",
        "category": "TEMPORAL",
        "unit": "flag",
        "reason_code": "WEEKEND_ACTIVITY",
        "risk_headline": "Weekend Activity Pattern",
        "mitigating_headline": "Weekday Activity Pattern",
        "risk_template": "Transaction was conducted during the weekend, departing from weekday baseline.",
        "mitigating_template": "Weekday transaction timing matches standard cardholder behavior.",
        "is_categorical": False,
    },
    "is_night": {
        "display_name": "Late-Night Indicator",
        "category": "TEMPORAL",
        "unit": "flag",
        "reason_code": "LATE_NIGHT_TRANSACTION",
        "risk_headline": "Late-Night Transaction Activity",
        "mitigating_headline": "Daylight Hours Activity",
        "risk_template": "Transaction executed during overnight off-hours (22:00 to 06:00).",
        "mitigating_template": "Transaction executed during regular daytime activity hours.",
        "is_categorical": False,
    },
    "hour_sin": {
        "display_name": "Cyclic Hour (Sine)",
        "category": "TEMPORAL",
        "unit": "cyclic",
        "reason_code": "CYCLIC_HOUR_DEVIATION",
        "risk_headline": "Cyclic Time Component Shift",
        "mitigating_headline": "Expected Cyclic Time",
        "risk_template": "Cyclic hour sine component ({raw_value:.4f}) reflects off-peak temporal risk.",
        "mitigating_template": "Cyclic hour sine component ({raw_value:.4f}) is typical.",
        "is_categorical": False,
    },
    "hour_cos": {
        "display_name": "Cyclic Hour (Cosine)",
        "category": "TEMPORAL",
        "unit": "cyclic",
        "reason_code": "CYCLIC_HOUR_DEVIATION",
        "risk_headline": "Cyclic Time Component Shift",
        "mitigating_headline": "Expected Cyclic Time",
        "risk_template": "Cyclic hour cosine component ({raw_value:.4f}) reflects off-peak temporal risk.",
        "mitigating_template": "Cyclic hour cosine component ({raw_value:.4f}) is typical.",
        "is_categorical": False,
    },
    "day_of_week_sin": {
        "display_name": "Cyclic Day-of-Week (Sine)",
        "category": "TEMPORAL",
        "unit": "cyclic",
        "reason_code": "CYCLIC_DAY_DEVIATION",
        "risk_headline": "Weekly Cycle Timing Anomaly",
        "mitigating_headline": "Expected Weekly Timing",
        "risk_template": "Weekly cyclic sine component ({raw_value:.4f}) shows deviation from typical rhythm.",
        "mitigating_template": "Weekly cyclic sine component ({raw_value:.4f}) is standard.",
        "is_categorical": False,
    },
    "day_of_week_cos": {
        "display_name": "Cyclic Day-of-Week (Cosine)",
        "category": "TEMPORAL",
        "unit": "cyclic",
        "reason_code": "CYCLIC_DAY_DEVIATION",
        "risk_headline": "Weekly Cycle Timing Anomaly",
        "mitigating_headline": "Expected Weekly Timing",
        "risk_template": "Weekly cyclic cosine component ({raw_value:.4f}) shows deviation from typical rhythm.",
        "mitigating_template": "Weekly cyclic cosine component ({raw_value:.4f}) is standard.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Transaction Velocity Features (6)
    # ---------------------------------------------------------
    "txn_count_1h": {
        "display_name": "1-Hour Transaction Velocity",
        "category": "VELOCITY",
        "unit": "txns",
        "reason_code": "VELOCITY_BURST_1H",
        "risk_headline": "Rapid 1-Hour Velocity Burst",
        "mitigating_headline": "Normal 1-Hour Transaction Velocity",
        "risk_template": "Unusual burst of {raw_value:.0f} transactions initiated within the last 1 hour.",
        "mitigating_template": "Single or low transaction count ({raw_value:.0f}) within the last hour.",
        "is_categorical": False,
    },
    "txn_count_6h": {
        "display_name": "6-Hour Transaction Velocity",
        "category": "VELOCITY",
        "unit": "txns",
        "reason_code": "VELOCITY_BURST_6H",
        "risk_headline": "Elevated 6-Hour Velocity",
        "mitigating_headline": "Normal 6-Hour Velocity",
        "risk_template": "Elevated volume of {raw_value:.0f} transactions within a 6-hour window.",
        "mitigating_template": "Moderate transaction volume ({raw_value:.0f}) over the last 6 hours.",
        "is_categorical": False,
    },
    "txn_count_24h": {
        "display_name": "24-Hour Transaction Velocity",
        "category": "VELOCITY",
        "unit": "txns",
        "reason_code": "VELOCITY_BURST_24H",
        "risk_headline": "High 24-Hour Transaction Count",
        "mitigating_headline": "Normal 24-Hour Transaction Count",
        "risk_template": "High cumulative frequency of {raw_value:.0f} transactions over the past 24 hours.",
        "mitigating_template": "Normal daily transaction frequency ({raw_value:.0f} transactions in 24h).",
        "is_categorical": False,
    },
    "txn_count_7d": {
        "display_name": "7-Day Transaction Count",
        "category": "VELOCITY",
        "unit": "txns",
        "reason_code": "ELEVATED_7D_VELOCITY",
        "risk_headline": "Elevated 7-Day Velocity",
        "mitigating_headline": "Normal 7-Day Velocity",
        "risk_template": "Unusually high 7-day velocity with {raw_value:.0f} transactions recorded.",
        "mitigating_template": "7-day transaction count ({raw_value:.0f}) aligns with baseline activity.",
        "is_categorical": False,
    },
    "txn_count_30d": {
        "display_name": "30-Day Transaction Count",
        "category": "VELOCITY",
        "unit": "txns",
        "reason_code": "ELEVATED_30D_VELOCITY",
        "risk_headline": "High Monthly Velocity",
        "mitigating_headline": "Standard Monthly Velocity",
        "risk_template": "High monthly activity with {raw_value:.0f} transactions over the past 30 days.",
        "mitigating_template": "Established 30-day transaction volume ({raw_value:.0f} txns) indicates steady account usage.",
        "is_categorical": False,
    },
    "time_since_prev_txn_seconds": {
        "display_name": "Time Since Previous Transaction",
        "category": "VELOCITY",
        "unit": "seconds",
        "reason_code": "RAPID_SUCCESSION_TRANSACTION",
        "risk_headline": "Rapid Succession Transaction",
        "mitigating_headline": "Adequate Time Interval Between Transactions",
        "risk_template": "Executed only {raw_value:.1f} seconds after the prior transaction on this account.",
        "mitigating_template": "Adequate interval ({raw_value:,.0f} seconds) since previous transaction.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Account State & Spending Aggregations (8)
    # ---------------------------------------------------------
    "is_first_account_txn": {
        "display_name": "First Account Transaction Indicator",
        "category": "ACCOUNT_HISTORY",
        "unit": "flag",
        "reason_code": "NEW_ACCOUNT_FIRST_TRANSACTION",
        "risk_headline": "First Transaction on New Account",
        "mitigating_headline": "Established Account History",
        "risk_template": "First transaction initiated on this account profile with zero prior history.",
        "mitigating_template": "Account has established historical transaction history.",
        "is_categorical": False,
    },
    "amt_sum_1h": {
        "display_name": "1-Hour Total Spend",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "HIGH_1H_CUMULATIVE_SPEND",
        "risk_headline": "High 1-Hour Cumulative Spend",
        "mitigating_headline": "Moderate 1-Hour Cumulative Spend",
        "risk_template": "Cumulative spend of ${raw_value:,.2f} within 1 hour indicates rapid funds outflow.",
        "mitigating_template": "1-hour total spend (${raw_value:,.2f}) is within normal limits.",
        "is_categorical": False,
    },
    "amt_sum_24h": {
        "display_name": "24-Hour Total Spend",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "HIGH_24H_CUMULATIVE_SPEND",
        "risk_headline": "High 24-Hour Cumulative Spend",
        "mitigating_headline": "Moderate 24-Hour Cumulative Spend",
        "risk_template": "Total 24-hour spend reached ${raw_value:,.2f}, surpassing standard daily thresholds.",
        "mitigating_template": "24-hour spend of ${raw_value:,.2f} is well within expected daily volume.",
        "is_categorical": False,
    },
    "amt_sum_7d": {
        "display_name": "7-Day Total Spend",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "HIGH_7D_CUMULATIVE_SPEND",
        "risk_headline": "Elevated 7-Day Total Spend",
        "mitigating_headline": "Moderate 7-Day Total Spend",
        "risk_template": "7-day cumulative spend of ${raw_value:,.2f} indicates elevated spending velocity.",
        "mitigating_template": "7-day cumulative spend (${raw_value:,.2f}) matches historical patterns.",
        "is_categorical": False,
    },
    "amt_sum_30d": {
        "display_name": "30-Day Total Spend",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "HIGH_30D_CUMULATIVE_SPEND",
        "risk_headline": "Elevated 30-Day Total Spend",
        "mitigating_headline": "Moderate 30-Day Total Spend",
        "risk_template": "30-day cumulative spend of ${raw_value:,.2f} reflects an aggressive monthly surge.",
        "mitigating_template": "30-day cumulative spend (${raw_value:,.2f}) reflects established financial history.",
        "is_categorical": False,
    },
    "amt_mean_24h": {
        "display_name": "24-Hour Average Amount",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "ELEVATED_24H_AVG_AMOUNT",
        "risk_headline": "Elevated 24-Hour Average Ticket Size",
        "mitigating_headline": "Standard 24-Hour Average Ticket Size",
        "risk_template": "24-hour average transaction amount (${raw_value:,.2f}) is significantly elevated.",
        "mitigating_template": "24-hour average transaction amount (${raw_value:,.2f}) is standard.",
        "is_categorical": False,
    },
    "amt_mean_7d": {
        "display_name": "7-Day Average Amount",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "ELEVATED_7D_AVG_AMOUNT",
        "risk_headline": "Elevated 7-Day Average Ticket Size",
        "mitigating_headline": "Standard 7-Day Average Ticket Size",
        "risk_template": "7-day average transaction amount (${raw_value:,.2f}) deviates from historical baseline.",
        "mitigating_template": "7-day average transaction amount (${raw_value:,.2f}) is consistent.",
        "is_categorical": False,
    },
    "amt_max_24h": {
        "display_name": "24-Hour Maximum Amount",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "ELEVATED_24H_MAX_AMOUNT",
        "risk_headline": "High 24-Hour Single Transaction Peak",
        "mitigating_headline": "Moderate 24-Hour Transaction Peak",
        "risk_template": "Peak transaction amount over the last 24 hours reached ${raw_value:,.2f}.",
        "mitigating_template": "Peak 24-hour transaction amount (${raw_value:,.2f}) is moderate.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Statistical Profile & Deviation Metrics (6)
    # ---------------------------------------------------------
    "amt_median_30d": {
        "display_name": "30-Day Median Amount",
        "category": "AMOUNT",
        "unit": "$ USD",
        "reason_code": "MEDIAN_AMOUNT_OUTLIER",
        "risk_headline": "Atypical 30-Day Median Amount",
        "mitigating_headline": "Standard 30-Day Median Amount",
        "risk_template": "30-day median transaction size (${raw_value:,.2f}) reflects shifting account profile.",
        "mitigating_template": "30-day median transaction size (${raw_value:,.2f}) indicates stable account profile.",
        "is_categorical": False,
    },
    "historical_amount_mean": {
        "display_name": "Cardholder Historical Mean Amount",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "HISTORICAL_MEAN_DEVIATION",
        "risk_headline": "Historical Average Spend Disparity",
        "mitigating_headline": "Consistent with Historical Average",
        "risk_template": "Cardholder historical mean transaction value is ${raw_value:,.2f}.",
        "mitigating_template": "Cardholder historical mean spend of ${raw_value:,.2f} provides strong baseline stability.",
        "is_categorical": False,
    },
    "historical_amount_std": {
        "display_name": "Historical Amount Standard Deviation",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "HISTORICAL_VOLATILITY",
        "risk_headline": "High Spending Volatility",
        "mitigating_headline": "Low Spending Volatility",
        "risk_template": "Cardholder exhibits historical spending volatility (σ = ${raw_value:,.2f}).",
        "mitigating_template": "Consistent cardholder spending profile with low variance (σ = ${raw_value:,.2f}).",
        "is_categorical": False,
    },
    "historical_amount_median": {
        "display_name": "Historical Median Amount",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "HISTORICAL_MEDIAN_DISPARITY",
        "risk_headline": "Deviation from Typical Ticket Size",
        "mitigating_headline": "Aligned with Typical Ticket Size",
        "risk_template": "Historical median spend (${raw_value:,.2f}) contrasts with current transaction size.",
        "mitigating_template": "Historical median spend (${raw_value:,.2f}) confirms regular purchase size.",
        "is_categorical": False,
    },
    "amount_zscore": {
        "display_name": "Spending Z-Score Deviation",
        "category": "AMOUNT",
        "unit": "σ",
        "reason_code": "HIGH_AMOUNT_ZSCORE",
        "risk_headline": "Extreme Statistical Spending Surge",
        "mitigating_headline": "Normal Spending Z-Score",
        "risk_template": "Transaction amount deviates by {raw_value:+.2f} standard deviations from cardholder baseline.",
        "mitigating_template": "Transaction amount is within {raw_value:+.2f} standard deviations of cardholder baseline.",
        "is_categorical": False,
    },
    "amount_ratio_to_historical_mean": {
        "display_name": "Amount to Historical Mean Ratio",
        "category": "AMOUNT",
        "unit": "ratio",
        "reason_code": "AMOUNT_RATIO_SURGE",
        "risk_headline": "Large Multiple of Historical Mean Spend",
        "mitigating_headline": "Standard Spend-to-Mean Ratio",
        "risk_template": "Purchase amount is {raw_value:.1f}x the cardholder's historical average transaction size.",
        "mitigating_template": "Purchase amount ratio ({raw_value:.2f}x historical mean) is within expected variance.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Account Behavioral Profile History (10)
    # ---------------------------------------------------------
    "account_txn_count_before": {
        "display_name": "Prior Account Lifetime Transactions",
        "category": "ACCOUNT_HISTORY",
        "unit": "txns",
        "reason_code": "LIMITED_ACCOUNT_TENURE",
        "risk_headline": "Limited Account Lifetime History",
        "mitigating_headline": "Mature Account Lifetime History",
        "risk_template": "Account has limited lifetime history with only {raw_value:.0f} prior transactions.",
        "mitigating_template": "Mature account with {raw_value:,.0f} prior successful lifetime transactions.",
        "is_categorical": False,
    },
    "account_total_spend_before": {
        "display_name": "Prior Account Lifetime Spend",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "LOW_LIFETIME_SPEND",
        "risk_headline": "Low Cumulative Account Spend",
        "mitigating_headline": "High Cumulative Account Spend",
        "risk_template": "Total historical lifetime spend is low (${raw_value:,.2f}), limiting established baseline.",
        "mitigating_template": "Established cumulative lifetime account spend of ${raw_value:,.2f}.",
        "is_categorical": False,
    },
    "account_avg_amount_before": {
        "display_name": "Prior Account Average Amount",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "LIFETIME_AVG_DISPARITY",
        "risk_headline": "Disparity from Lifetime Average",
        "mitigating_headline": "Aligned with Lifetime Average",
        "risk_template": "Prior account average amount (${raw_value:,.2f}) indicates potential ticket size anomaly.",
        "mitigating_template": "Prior account average amount (${raw_value:,.2f}) matches current behavior.",
        "is_categorical": False,
    },
    "account_max_amount_before": {
        "display_name": "Prior Account Max Amount",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "EXCEEDS_LIFETIME_MAX",
        "risk_headline": "Transaction Size Surpasses Historical Maximum",
        "mitigating_headline": "Within Lifetime Maximum Bounds",
        "risk_template": "Current purchase approaches or exceeds prior historical maximum (${raw_value:,.2f}).",
        "mitigating_template": "Transaction is safely below prior historical maximum (${raw_value:,.2f}).",
        "is_categorical": False,
    },
    "account_unique_merchant_count_before": {
        "display_name": "Prior Unique Merchant Count",
        "category": "ACCOUNT_HISTORY",
        "unit": "merchants",
        "reason_code": "LOW_MERCHANT_DIVERSITY",
        "risk_headline": "Low Historical Merchant Diversity",
        "mitigating_headline": "Broad Historical Merchant Diversity",
        "risk_template": "Account has interacted with only {raw_value:.0f} unique merchants historically.",
        "mitigating_template": "Account has an established footprint across {raw_value:,.0f} unique merchants.",
        "is_categorical": False,
    },
    "account_unique_category_count_before": {
        "display_name": "Prior Unique Category Count",
        "category": "ACCOUNT_HISTORY",
        "unit": "categories",
        "reason_code": "LOW_CATEGORY_DIVERSITY",
        "risk_headline": "Low Historical Category Diversity",
        "mitigating_headline": "Broad Historical Category Diversity",
        "risk_template": "Account has interacted with only {raw_value:.0f} merchant categories historically.",
        "mitigating_template": "Account has active history across {raw_value:.0f} merchant categories.",
        "is_categorical": False,
    },
    "account_merchant_txn_count_before": {
        "display_name": "Prior Transactions with this Merchant",
        "category": "ACCOUNT_HISTORY",
        "unit": "txns",
        "reason_code": "FIRST_TIME_MERCHANT_VISIT",
        "risk_headline": "First-Time or Rare Merchant Interaction",
        "mitigating_headline": "Familiar Merchant Interaction",
        "risk_template": "Cardholder has only {raw_value:.0f} prior transactions with this specific merchant.",
        "mitigating_template": "Cardholder has an established history ({raw_value:.0f} txns) with this merchant.",
        "is_categorical": False,
    },
    "account_category_txn_count_before": {
        "display_name": "Prior Transactions in this Category",
        "category": "ACCOUNT_HISTORY",
        "unit": "txns",
        "reason_code": "NEW_CATEGORY_INTERACTION",
        "risk_headline": "Infrequent Category Interaction",
        "mitigating_headline": "Frequent Category Interaction",
        "risk_template": "Cardholder has only {raw_value:.0f} prior transactions in this merchant category.",
        "mitigating_template": "Cardholder frequently transacts in this category ({raw_value:.0f} prior txns).",
        "is_categorical": False,
    },
    "account_merchant_spend_before": {
        "display_name": "Prior Spend with this Merchant",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "LOW_HISTORICAL_MERCHANT_SPEND",
        "risk_headline": "Low Historical Spend with Merchant",
        "mitigating_headline": "Established Spend with Merchant",
        "risk_template": "Cardholder has spent only ${raw_value:,.2f} with this merchant previously.",
        "mitigating_template": "Cardholder has established cumulative spend of ${raw_value:,.2f} with this merchant.",
        "is_categorical": False,
    },
    "account_category_spend_before": {
        "display_name": "Prior Spend in this Category",
        "category": "ACCOUNT_HISTORY",
        "unit": "$ USD",
        "reason_code": "LOW_HISTORICAL_CATEGORY_SPEND",
        "risk_headline": "Low Historical Spend in Category",
        "mitigating_headline": "Established Spend in Category",
        "risk_template": "Cardholder has spent only ${raw_value:,.2f} in this merchant category historically.",
        "mitigating_template": "Cardholder has substantial spend history (${raw_value:,.2f}) in this category.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Global Merchant & Category Interaction Statistics (2)
    # ---------------------------------------------------------
    "merchant_txn_count_before": {
        "display_name": "Merchant Global Transaction Volume",
        "category": "ACCOUNT_HISTORY",
        "unit": "txns",
        "reason_code": "LOW_VOLUME_MERCHANT",
        "risk_headline": "Low Global Merchant Processing Volume",
        "mitigating_headline": "High-Volume Trusted Merchant",
        "risk_template": "Merchant has low overall system transaction history ({raw_value:,.0f} global txns).",
        "mitigating_template": "High-volume merchant with {raw_value:,.0f} platform transactions.",
        "is_categorical": False,
    },
    "category_txn_count_before": {
        "display_name": "Category Global Transaction Volume",
        "category": "ACCOUNT_HISTORY",
        "unit": "txns",
        "reason_code": "LOW_VOLUME_CATEGORY",
        "risk_headline": "Low-Volume Merchant Category",
        "mitigating_headline": "Mainstream Merchant Category",
        "risk_template": "Category represents a niche processing vertical ({raw_value:,.0f} global txns).",
        "mitigating_template": "Mainstream retail category with {raw_value:,.0f} global transactions.",
        "is_categorical": False,
    },

    # ---------------------------------------------------------
    # Geospatial Distance & Velocity Features (4)
    # ---------------------------------------------------------
    "cardholder_merchant_distance_km": {
        "display_name": "Cardholder to Merchant Distance",
        "category": "GEOGRAPHY",
        "unit": "km",
        "reason_code": "FAR_CARDHOLDER_MERCHANT_DISTANCE",
        "risk_headline": "Large Geographic Separation",
        "mitigating_headline": "Local Proximity Transaction",
        "risk_template": "Cardholder and merchant are separated by {raw_value:,.1f} km, indicating a remote transaction.",
        "mitigating_template": "Merchant is located in close proximity ({raw_value:,.1f} km) to cardholder residence.",
        "is_categorical": False,
    },
    "distance_from_prev_merchant_km": {
        "display_name": "Distance from Previous Merchant",
        "category": "GEOGRAPHY",
        "unit": "km",
        "reason_code": "LARGE_DISTANCE_JUMP",
        "risk_headline": "Large Geographic Location Jump",
        "mitigating_headline": "Nearby Sequential Merchant",
        "risk_template": "Merchant location is {raw_value:,.1f} km away from the cardholder's prior transaction location.",
        "mitigating_template": "Location is consistent with prior transaction location ({raw_value:,.1f} km jump).",
        "is_categorical": False,
    },
    "implied_travel_speed_kmh": {
        "display_name": "Implied Travel Speed",
        "category": "GEOGRAPHY",
        "unit": "km/h",
        "reason_code": "HIGH_IMPLIED_TRAVEL_SPEED",
        "risk_headline": "Elevated Geographic Travel Speed",
        "mitigating_headline": "Feasible Geographic Speed",
        "risk_template": "Implied transit speed of {raw_value:,.1f} km/h between sequential transaction locations.",
        "mitigating_template": "Implied travel speed ({raw_value:,.1f} km/h) is physically feasible.",
        "is_categorical": False,
    },
    "is_impossible_travel_speed": {
        "display_name": "Impossible Travel Speed Indicator",
        "category": "GEOGRAPHY",
        "unit": "flag",
        "reason_code": "IMPOSSIBLE_TRAVEL_SPEED",
        "risk_headline": "Physically Impossible Travel Speed Signal",
        "mitigating_headline": "Normal Geographic Travel Feasibility",
        "risk_template": "Speed between sequential transactions exceeds physical travel limits (>1000 km/h).",
        "mitigating_template": "Sequential transaction timing and distance conform to normal physical constraints.",
        "is_categorical": False,
    },
}

# Immutable mapping proxy
FEATURE_METADATA_REGISTRY: Mapping[str, Mapping[str, Any]] = MappingProxyType({
    k: MappingProxyType(v) for k, v in FEATURE_REGISTRY.items()
})


def get_feature_metadata(feature_name: str) -> Mapping[str, Any]:
    """
    Retrieve immutable metadata for a predictive feature.

    Args:
        feature_name: Feature name string.

    Returns:
        Mapping[str, Any]: Immutable feature metadata dictionary.

    Raises:
        KeyError: If feature_name is not registered in PREDICTIVE_FEATURE_COLUMNS.
    """
    if feature_name not in FEATURE_METADATA_REGISTRY:
        raise KeyError(f"Unknown feature '{feature_name}'. Registered features: {list(FEATURE_METADATA_REGISTRY.keys())[:5]}")
    return FEATURE_METADATA_REGISTRY[feature_name]
