/**
 * Canonical UI Feature Metadata Catalog for 55 Predictive Features.
 * 
 * NOTE: This file provides UI presentation metadata only (display labels, category groupings,
 * slider step sizes, input ranges, and tooltips). Backend validation in TransactionPredictRequest
 * is the sole source of truth for validation rules.
 */

export interface FeatureMetadata {
  name: string;
  label: string;
  category: string;
  defaultValue: number | string;
  min?: number;
  max?: number;
  step?: number;
  type: 'number' | 'slider' | 'select' | 'text';
  options?: string[];
  description: string;
}

export const FEATURE_CATEGORIES: string[] = [
  'General & Core Predictors',
  'Velocity & Frequency',
  'Spending & Monetary Volume',
  'Spending Deviation & Z-Scores',
  'Account History & Diversity',
  'Merchant & Category Interactions',
  'Geographic & Impossible Travel',
  'Temporal & Periodicity',
];

export const CANONICAL_FEATURES: FeatureMetadata[] = [
  // General & Core Predictors (8 features)
  {
    name: 'amount',
    label: 'Transaction Amount ($)',
    category: 'General & Core Predictors',
    defaultValue: 85.50,
    min: 0.0,
    max: 10000.0,
    step: 0.5,
    type: 'number',
    description: 'Transaction amount in USD (must be >= 0.0)',
  },
  {
    name: 'cardholder_lat',
    label: 'Cardholder Latitude',
    category: 'General & Core Predictors',
    defaultValue: 40.7128,
    min: -90.0,
    max: 90.0,
    step: 0.0001,
    type: 'number',
    description: 'Latitude of cardholder home residence (-90 to 90)',
  },
  {
    name: 'cardholder_long',
    label: 'Cardholder Longitude',
    category: 'General & Core Predictors',
    defaultValue: -74.0060,
    min: -180.0,
    max: 180.0,
    step: 0.0001,
    type: 'number',
    description: 'Longitude of cardholder home residence (-180 to 180)',
  },
  {
    name: 'merchant_lat',
    label: 'Merchant Latitude',
    category: 'General & Core Predictors',
    defaultValue: 40.7306,
    min: -90.0,
    max: 90.0,
    step: 0.0001,
    type: 'number',
    description: 'Latitude of merchant location (-90 to 90)',
  },
  {
    name: 'merchant_long',
    label: 'Merchant Longitude',
    category: 'General & Core Predictors',
    defaultValue: -73.9352,
    min: -180.0,
    max: 180.0,
    step: 0.0001,
    type: 'number',
    description: 'Longitude of merchant location (-180 to 180)',
  },
  {
    name: 'city_pop',
    label: 'City Population',
    category: 'General & Core Predictors',
    defaultValue: 8336817,
    min: 0,
    max: 20000000,
    step: 1000,
    type: 'number',
    description: 'Cardholder city population',
  },
  {
    name: 'merchant_category',
    label: 'Merchant Category',
    category: 'General & Core Predictors',
    defaultValue: 'retail',
    type: 'select',
    options: [
      'retail',
      'grocery',
      'dining',
      'travel',
      'electronics',
      'entertainment',
      'utilities',
      'pharmacy',
      'jewelry',
      'automotive',
      'services',
    ],
    description: 'Primary industry classification of merchant',
  },
  {
    name: 'job_category',
    label: 'Cardholder Job Category',
    category: 'General & Core Predictors',
    defaultValue: 'management',
    type: 'select',
    options: [
      'management',
      'engineering',
      'finance',
      'healthcare',
      'education',
      'sales',
      'service',
      'technology',
      'retired',
      'legal',
    ],
    description: 'Cardholder job or profession group',
  },

  // Velocity & Frequency (7 features)
  {
    name: 'txn_count_1h',
    label: 'Txn Count (Past 1h)',
    category: 'Velocity & Frequency',
    defaultValue: 1,
    min: 0,
    max: 50,
    step: 1,
    type: 'slider',
    description: 'Number of account transactions in the past 1 hour',
  },
  {
    name: 'txn_count_6h',
    label: 'Txn Count (Past 6h)',
    category: 'Velocity & Frequency',
    defaultValue: 2,
    min: 0,
    max: 100,
    step: 1,
    type: 'slider',
    description: 'Number of account transactions in the past 6 hours',
  },
  {
    name: 'txn_count_24h',
    label: 'Txn Count (Past 24h)',
    category: 'Velocity & Frequency',
    defaultValue: 4,
    min: 0,
    max: 200,
    step: 1,
    type: 'slider',
    description: 'Number of account transactions in the past 24 hours',
  },
  {
    name: 'txn_count_7d',
    label: 'Txn Count (Past 7d)',
    category: 'Velocity & Frequency',
    defaultValue: 18,
    min: 0,
    max: 500,
    step: 1,
    type: 'number',
    description: 'Number of account transactions in the past 7 days',
  },
  {
    name: 'txn_count_30d',
    label: 'Txn Count (Past 30d)',
    category: 'Velocity & Frequency',
    defaultValue: 65,
    min: 0,
    max: 2000,
    step: 1,
    type: 'number',
    description: 'Number of account transactions in the past 30 days',
  },
  {
    name: 'time_since_prev_txn_seconds',
    label: 'Time Since Previous Txn (s)',
    category: 'Velocity & Frequency',
    defaultValue: 3600.0,
    min: 0.0,
    max: 864000.0,
    step: 60.0,
    type: 'number',
    description: 'Elapsed seconds since prior transaction on this account',
  },
  {
    name: 'is_first_account_txn',
    label: 'First Account Txn Flag',
    category: 'Velocity & Frequency',
    defaultValue: 0,
    type: 'select',
    options: ['0', '1'],
    description: 'Binary flag: 1 if this is the first recorded transaction for this account',
  },

  // Spending & Monetary Volume (8 features)
  {
    name: 'amt_sum_1h',
    label: 'Amount Sum (Past 1h)',
    category: 'Spending & Monetary Volume',
    defaultValue: 85.50,
    min: 0.0,
    max: 20000.0,
    step: 5.0,
    type: 'number',
    description: 'Total cumulative dollar volume in past 1 hour',
  },
  {
    name: 'amt_sum_24h',
    label: 'Amount Sum (Past 24h)',
    category: 'Spending & Monetary Volume',
    defaultValue: 240.00,
    min: 0.0,
    max: 50000.0,
    step: 10.0,
    type: 'number',
    description: 'Total cumulative dollar volume in past 24 hours',
  },
  {
    name: 'amt_sum_7d',
    label: 'Amount Sum (Past 7d)',
    category: 'Spending & Monetary Volume',
    defaultValue: 1150.00,
    min: 0.0,
    max: 200000.0,
    step: 50.0,
    type: 'number',
    description: 'Total cumulative dollar volume in past 7 days',
  },
  {
    name: 'amt_sum_30d',
    label: 'Amount Sum (Past 30d)',
    category: 'Spending & Monetary Volume',
    defaultValue: 4200.00,
    min: 0.0,
    max: 500000.0,
    step: 100.0,
    type: 'number',
    description: 'Total cumulative dollar volume in past 30 days',
  },
  {
    name: 'amt_mean_24h',
    label: 'Mean Amount (Past 24h)',
    category: 'Spending & Monetary Volume',
    defaultValue: 60.00,
    min: 0.0,
    max: 10000.0,
    step: 5.0,
    type: 'number',
    description: 'Average transaction amount in past 24 hours',
  },
  {
    name: 'amt_mean_7d',
    label: 'Mean Amount (Past 7d)',
    category: 'Spending & Monetary Volume',
    defaultValue: 63.88,
    min: 0.0,
    max: 10000.0,
    step: 5.0,
    type: 'number',
    description: 'Average transaction amount in past 7 days',
  },
  {
    name: 'amt_max_24h',
    label: 'Max Amount (Past 24h)',
    category: 'Spending & Monetary Volume',
    defaultValue: 120.00,
    min: 0.0,
    max: 20000.0,
    step: 10.0,
    type: 'number',
    description: 'Maximum single transaction amount in past 24 hours',
  },
  {
    name: 'amt_median_30d',
    label: 'Median Amount (Past 30d)',
    category: 'Spending & Monetary Volume',
    defaultValue: 55.00,
    min: 0.0,
    max: 10000.0,
    step: 5.0,
    type: 'number',
    description: 'Median transaction amount in past 30 days',
  },

  // Spending Deviation & Z-Scores (5 features)
  {
    name: 'historical_amount_mean',
    label: 'Historical Amount Mean',
    category: 'Spending Deviation & Z-Scores',
    defaultValue: 65.00,
    min: 0.0,
    max: 10000.0,
    step: 5.0,
    type: 'number',
    description: 'Historical baseline mean transaction amount for this account',
  },
  {
    name: 'historical_amount_std',
    label: 'Historical Amount StdDev',
    category: 'Spending Deviation & Z-Scores',
    defaultValue: 25.00,
    min: 0.1,
    max: 5000.0,
    step: 1.0,
    type: 'number',
    description: 'Historical baseline standard deviation for this account',
  },
  {
    name: 'historical_amount_median',
    label: 'Historical Amount Median',
    category: 'Spending Deviation & Z-Scores',
    defaultValue: 58.00,
    min: 0.0,
    max: 10000.0,
    step: 5.0,
    type: 'number',
    description: 'Historical baseline median amount for this account',
  },
  {
    name: 'amount_zscore',
    label: 'Amount Z-Score',
    category: 'Spending Deviation & Z-Scores',
    defaultValue: 0.82,
    min: -5.0,
    max: 15.0,
    step: 0.05,
    type: 'slider',
    description: 'Standard deviations current amount deviates from historical mean',
  },
  {
    name: 'amount_ratio_to_historical_mean',
    label: 'Ratio to Historical Mean',
    category: 'Spending Deviation & Z-Scores',
    defaultValue: 1.31,
    min: 0.0,
    max: 50.0,
    step: 0.1,
    type: 'number',
    description: 'Current amount divided by historical mean amount',
  },

  // Account History & Diversity (6 features)
  {
    name: 'account_txn_count_before',
    label: 'Total Prior Txn Count',
    category: 'Account History & Diversity',
    defaultValue: 142,
    min: 0,
    max: 10000,
    step: 1,
    type: 'number',
    description: 'Total lifetime transaction count for account prior to this event',
  },
  {
    name: 'account_total_spend_before',
    label: 'Total Lifetime Spend',
    category: 'Account History & Diversity',
    defaultValue: 9230.00,
    min: 0.0,
    max: 1000000.0,
    step: 50.0,
    type: 'number',
    description: 'Total lifetime spending volume for account prior to this event',
  },
  {
    name: 'account_avg_amount_before',
    label: 'Lifetime Average Amount',
    category: 'Account History & Diversity',
    defaultValue: 65.00,
    min: 0.0,
    max: 10000.0,
    step: 5.0,
    type: 'number',
    description: 'Lifetime mean transaction amount on this account',
  },
  {
    name: 'account_max_amount_before',
    label: 'Lifetime Max Amount',
    category: 'Account History & Diversity',
    defaultValue: 450.00,
    min: 0.0,
    max: 50000.0,
    step: 25.0,
    type: 'number',
    description: 'Largest single transaction previously executed on this account',
  },
  {
    name: 'account_unique_merchant_count_before',
    label: 'Unique Merchants Visited',
    category: 'Account History & Diversity',
    defaultValue: 48,
    min: 0,
    max: 1000,
    step: 1,
    type: 'number',
    description: 'Distinct merchants visited historically by this account',
  },
  {
    name: 'account_unique_category_count_before',
    label: 'Unique Categories Visited',
    category: 'Account History & Diversity',
    defaultValue: 9,
    min: 0,
    max: 20,
    step: 1,
    type: 'slider',
    description: 'Distinct merchant industry categories visited historically',
  },

  // Merchant & Category Interactions (6 features)
  {
    name: 'account_merchant_txn_count_before',
    label: 'Account Txns at this Merchant',
    category: 'Merchant & Category Interactions',
    defaultValue: 8,
    min: 0,
    max: 500,
    step: 1,
    type: 'slider',
    description: 'Prior transactions by this account at this specific merchant',
  },
  {
    name: 'account_category_txn_count_before',
    label: 'Account Txns in this Category',
    category: 'Merchant & Category Interactions',
    defaultValue: 35,
    min: 0,
    max: 1000,
    step: 1,
    type: 'number',
    description: 'Prior transactions by this account in this merchant category',
  },
  {
    name: 'account_merchant_spend_before',
    label: 'Account Spend at this Merchant',
    category: 'Merchant & Category Interactions',
    defaultValue: 520.00,
    min: 0.0,
    max: 50000.0,
    step: 20.0,
    type: 'number',
    description: 'Cumulative spending by this account at this specific merchant',
  },
  {
    name: 'account_category_spend_before',
    label: 'Account Spend in this Category',
    category: 'Merchant & Category Interactions',
    defaultValue: 2275.00,
    min: 0.0,
    max: 100000.0,
    step: 50.0,
    type: 'number',
    description: 'Cumulative spending by this account in this merchant category',
  },
  {
    name: 'merchant_txn_count_before',
    label: 'Global Merchant Txn Count',
    category: 'Merchant & Category Interactions',
    defaultValue: 1540,
    min: 0,
    max: 100000,
    step: 10,
    type: 'number',
    description: 'Global transaction count across all users at this merchant',
  },
  {
    name: 'category_txn_count_before',
    label: 'Global Category Txn Count',
    category: 'Merchant & Category Interactions',
    defaultValue: 45200,
    min: 0,
    max: 500000,
    step: 100,
    type: 'number',
    description: 'Global transaction count across all users in this category',
  },

  // Geographic & Impossible Travel (4 features)
  {
    name: 'cardholder_merchant_distance_km',
    label: 'Cardholder-Merchant Distance (km)',
    category: 'Geographic & Impossible Travel',
    defaultValue: 8.42,
    min: 0.0,
    max: 20000.0,
    step: 1.0,
    type: 'number',
    description: 'Great-circle distance (km) between cardholder home and merchant',
  },
  {
    name: 'distance_from_prev_merchant_km',
    label: 'Distance from Prior Merchant (km)',
    category: 'Geographic & Impossible Travel',
    defaultValue: 3.15,
    min: 0.0,
    max: 20000.0,
    step: 1.0,
    type: 'number',
    description: 'Distance (km) from previous transaction merchant location',
  },
  {
    name: 'implied_travel_speed_kmh',
    label: 'Implied Travel Speed (km/h)',
    category: 'Geographic & Impossible Travel',
    defaultValue: 12.6,
    min: 0.0,
    max: 2000.0,
    step: 5.0,
    type: 'number',
    description: 'Calculated travel speed (km/h) between consecutive transactions',
  },
  {
    name: 'is_impossible_travel_speed',
    label: 'Impossible Travel Flag (>800 km/h)',
    category: 'Geographic & Impossible Travel',
    defaultValue: 0,
    type: 'select',
    options: ['0', '1'],
    description: 'Flag indicating physically impossible transit speed between transactions',
  },

  // Temporal & Periodicity (11 features)
  {
    name: 'transaction_hour',
    label: 'Transaction Hour (0–23)',
    category: 'Temporal & Periodicity',
    defaultValue: 14,
    min: 0,
    max: 23,
    step: 1,
    type: 'slider',
    description: 'Hour of transaction execution (0 to 23)',
  },
  {
    name: 'day_of_week',
    label: 'Day of Week (0=Mon, 6=Sun)',
    category: 'Temporal & Periodicity',
    defaultValue: 2,
    min: 0,
    max: 6,
    step: 1,
    type: 'slider',
    description: 'Day of week index (0=Monday to 6=Sunday)',
  },
  {
    name: 'day_of_month',
    label: 'Day of Month (1–31)',
    category: 'Temporal & Periodicity',
    defaultValue: 15,
    min: 1,
    max: 31,
    step: 1,
    type: 'slider',
    description: 'Day of calendar month (1 to 31)',
  },
  {
    name: 'month',
    label: 'Month of Year (1–12)',
    category: 'Temporal & Periodicity',
    defaultValue: 9,
    min: 1,
    max: 12,
    step: 1,
    type: 'slider',
    description: 'Month of calendar year (1 to 12)',
  },
  {
    name: 'week_of_year',
    label: 'Week of Year (1–53)',
    category: 'Temporal & Periodicity',
    defaultValue: 38,
    min: 1,
    max: 53,
    step: 1,
    type: 'number',
    description: 'ISO week number of calendar year (1 to 53)',
  },
  {
    name: 'is_weekend',
    label: 'Weekend Flag (0 or 1)',
    category: 'Temporal & Periodicity',
    defaultValue: 0,
    type: 'select',
    options: ['0', '1'],
    description: '1 if transaction occurred on Saturday or Sunday, else 0',
  },
  {
    name: 'is_night',
    label: 'Overnight Flag (0 or 1)',
    category: 'Temporal & Periodicity',
    defaultValue: 0,
    type: 'select',
    options: ['0', '1'],
    description: '1 if transaction occurred between 23:00 and 06:00, else 0',
  },
  {
    name: 'hour_sin',
    label: 'Hour (Sine Transformed)',
    category: 'Temporal & Periodicity',
    defaultValue: -0.5,
    min: -1.0,
    max: 1.0,
    step: 0.01,
    type: 'number',
    description: 'Cyclical sine encoding of transaction hour',
  },
  {
    name: 'hour_cos',
    label: 'Hour (Cosine Transformed)',
    category: 'Temporal & Periodicity',
    defaultValue: -0.866,
    min: -1.0,
    max: 1.0,
    step: 0.01,
    type: 'number',
    description: 'Cyclical cosine encoding of transaction hour',
  },
  {
    name: 'day_of_week_sin',
    label: 'Day of Week (Sine Transformed)',
    category: 'Temporal & Periodicity',
    defaultValue: 0.975,
    min: -1.0,
    max: 1.0,
    step: 0.01,
    type: 'number',
    description: 'Cyclical sine encoding of day of week',
  },
  {
    name: 'day_of_week_cos',
    label: 'Day of Week (Cosine Transformed)',
    category: 'Temporal & Periodicity',
    defaultValue: -0.222,
    min: -1.0,
    max: 1.0,
    step: 0.01,
    type: 'number',
    description: 'Cyclical cosine encoding of day of week',
  },
];

/**
 * Generate default candidate feature dictionary covering all 55 canonical features.
 */
export function getDefaultSimulatedFeatures(): Record<string, any> {
  const defaults: Record<string, any> = {};
  for (const f of CANONICAL_FEATURES) {
    if (f.name === 'is_first_account_txn' || f.name === 'is_impossible_travel_speed' || f.name === 'is_weekend' || f.name === 'is_night') {
      defaults[f.name] = Number(f.defaultValue);
    } else {
      defaults[f.name] = f.defaultValue;
    }
  }
  return defaults;
}

/**
 * Demo preset scenarios conforming to the 55-feature contract.
 * Note: These are optional conveniences only and do not guarantee a specific risk score/tier.
 */
export interface DemoPreset {
  id: string;
  name: string;
  description: string;
  overrides: Record<string, any>;
}

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: 'velocity_spike',
    name: 'High-Velocity Spike',
    description: 'Elevated transaction burst (12 txns in past 1h) with short interval',
    overrides: {
      txn_count_1h: 12,
      txn_count_6h: 24,
      txn_count_24h: 35,
      time_since_prev_txn_seconds: 45.0,
      amt_sum_1h: 1450.00,
    },
  },
  {
    id: 'impossible_travel',
    name: 'Impossible Geographic Travel',
    description: 'Consecutive transactions separated by 4,500 km within 15 minutes (>1,200 km/h)',
    overrides: {
      distance_from_prev_merchant_km: 4500.0,
      cardholder_merchant_distance_km: 4520.0,
      time_since_prev_txn_seconds: 900.0,
      implied_travel_speed_kmh: 1250.0,
      is_impossible_travel_speed: 1,
    },
  },
  {
    id: 'large_amount_outlier',
    name: 'Extreme Monetary Outlier',
    description: 'High-value transaction ($4,850) with significant historical mean deviation (Z=8.5)',
    overrides: {
      amount: 4850.00,
      amount_zscore: 8.5,
      amount_ratio_to_historical_mean: 74.6,
      historical_amount_mean: 65.00,
      amt_sum_1h: 4850.00,
      amt_sum_24h: 5120.00,
    },
  },
  {
    id: 'normal_routine',
    name: 'Normal Routine Activity',
    description: 'Low-value everyday purchase ($18.50 grocery) matching historic patterns',
    overrides: {
      amount: 18.50,
      amount_zscore: -0.45,
      amount_ratio_to_historical_mean: 0.28,
      txn_count_1h: 1,
      txn_count_24h: 2,
      merchant_category: 'grocery',
      cardholder_merchant_distance_km: 2.1,
      implied_travel_speed_kmh: 8.0,
      is_impossible_travel_speed: 0,
    },
  },
];
