"""
Model Lifecycle Management, Registry, and Controlled Promotion Package for Phase 14.
"""

from ml.lifecycle.config import LifecycleConfig, default_lifecycle_config
from ml.lifecycle.dataset_builder import (
    DEFAULT_VALIDATION_CUTOFF,
    ChallengerDataset,
    ChallengerDatasetBuilder,
    ChallengerDatasetMetadata,
    map_disposition_to_label,
)
from ml.lifecycle.evaluation import (
    CandidateEvaluationResult,
    CandidateGateConfig,
    CandidateModelEvaluator,
    CandidateThresholdAnalyzer,
    EvaluationScope,
    FullCandidateEvaluationResult,
    GateResult,
    OperationalDecisionEvaluator,
    OperationalDecisionMetrics,
    ThresholdOptimizationObjective,
    ThresholdSelectionResult,
    ThresholdSweepPoint,
    calculate_evaluation_metrics,
    calculate_latency_distribution,
    default_candidate_gate_config,
    evaluate_candidate_gates,
    FullCandidateEvaluationPipeline,
    ChampionChallengerComparator,
    ChampionChallengerComparisonResult,
    ClassificationComparison,
    DeltaSign,
    LatencyComparison,
    MetricDelta,
    OperationalComparison,
    compute_metric_delta,
)
from ml.lifecycle.schemas import (
    ModelLifecycleStatus,
    ModelBundleManifest,
    EvaluationMetricsSummary,
    PromotionRecord,
    RollbackRecord,
    VALID_LIFECYCLE_TRANSITIONS,
    validate_semantic_version,
    validate_bundle_manifest,
    calculate_file_sha256,
    verify_bundle_integrity,
)
from ml.lifecycle.governance import (
    GateEvaluationRule,
    GateStatus,
    HumanSignOffEngine,
    PromotionEligibilityAssessment,
    PromotionGateBlockedError,
    PromotionGateEvaluator,
    PromotionGateResult,
    PromotionGateSpecification,
    PromotionSignOffRecord,
    SignOffConflictError,
    SignOffDecision,
    UnauthorizedSignOffActorError,
    compute_assessment_sha256,
    default_promotion_gate_specification,
)
from ml.lifecycle.training import (
    CandidateBundle,
    ChallengerTrainingConfig,
    ChallengerTrainingPipeline,
    ChampionImmutabilityViolationError,
    TrainingExecutionError,
    run_training_worker,
)

__all__ = [
    "LifecycleConfig",
    "default_lifecycle_config",
    "ModelLifecycleStatus",
    "ModelBundleManifest",
    "EvaluationMetricsSummary",
    "PromotionRecord",
    "RollbackRecord",
    "VALID_LIFECYCLE_TRANSITIONS",
    "validate_semantic_version",
    "validate_bundle_manifest",
    "calculate_file_sha256",
    "verify_bundle_integrity",
    # Dataset Builder
    "ChallengerDataset",
    "ChallengerDatasetBuilder",
    "ChallengerDatasetMetadata",
    "DEFAULT_VALIDATION_CUTOFF",
    "map_disposition_to_label",
    # Training Pipeline
    "ChallengerTrainingConfig",
    "CandidateBundle",
    "ChallengerTrainingPipeline",
    "ChampionImmutabilityViolationError",
    "TrainingExecutionError",
    "run_training_worker",
    # Evaluation
    "CandidateModelEvaluator",
    "CandidateEvaluationResult",
    "CandidateGateConfig",
    "default_candidate_gate_config",
    "evaluate_candidate_gates",
    "calculate_evaluation_metrics",
    "calculate_latency_distribution",
    "EvaluationScope",
    "GateResult",
    # Phase 14.3 Full Evaluation & Threshold Analysis
    "CandidateThresholdAnalyzer",
    "OperationalDecisionEvaluator",
    "FullCandidateEvaluationPipeline",
    "ThresholdOptimizationObjective",
    "ThresholdSweepPoint",
    "ThresholdSelectionResult",
    "OperationalDecisionMetrics",
    "FullCandidateEvaluationResult",
    # Phase 14.4 Champion vs. Challenger Comparator
    "ChampionChallengerComparator",
    "ChampionChallengerComparisonResult",
    "ClassificationComparison",
    "DeltaSign",
    "LatencyComparison",
    "MetricDelta",
    "OperationalComparison",
    "compute_metric_delta",
    # Phase 14.5 Promotion Governance & Human Sign-Off
    "PromotionGateSpecification",
    "default_promotion_gate_specification",
    "PromotionGateEvaluator",
    "EvidenceCorruptedError",
    "HumanSignOffEngine",
    "UnauthorizedSignOffActorError",
    "PromotionGateBlockedError",
    "SignOffConflictError",
    "compute_assessment_sha256",
    "GateEvaluationRule",
    "GateStatus",
    "PromotionEligibilityAssessment",
    "PromotionGateResult",
    "PromotionSignOffRecord",
    "SignOffDecision",
    # Phase 14.6 Staged Model Promotion & Rollback
    "ModelPromotionEngine",
    "ModelRollbackEngine",
    "PromotionRecoveryEngine",
    "create_synthetic_55_feature_dataframe",
    "PromotionOperationState",
    "PromotionOperationJournal",
    "PromotionExecutionRecord",
    "RollbackExecutionRecord",
    "PromotionResult",
    "RollbackResult",
    "PRE_COMMIT_STATES",
    "POST_COMMIT_STATES",
    "PromotionPreconditionError",
    "PromotionStagingError",
    "PromotionIntegrityError",
    "PromotionPostCommitVerificationError",
    "RollbackPreconditionError",
    "RollbackIntegrityError",
    "RecoveryRequiredError",
]

from ml.lifecycle.promotion import (
    ModelPromotionEngine,
    ModelRollbackEngine,
    PromotionRecoveryEngine,
    create_synthetic_55_feature_dataframe,
    PromotionOperationState,
    PromotionOperationJournal,
    PromotionExecutionRecord,
    RollbackExecutionRecord,
    PromotionResult,
    RollbackResult,
    PRE_COMMIT_STATES,
    POST_COMMIT_STATES,
    PromotionPreconditionError,
    PromotionStagingError,
    PromotionIntegrityError,
    PromotionPostCommitVerificationError,
    RollbackPreconditionError,
    RollbackIntegrityError,
    RecoveryRequiredError,
)


